#!/bin/bash

git clone git@github.com:Senzing/accountant-aws-marketplace.git
git clone git@github.com:Senzing/ansible-playbook-demo.git
git clone git@github.com:Senzing/ansible-role-senzingapi.git
git clone git@github.com:Senzing/ansible-role-stream-producer.git
git clone git@github.com:Senzing/awesome.git
git clone git@github.com:Senzing/aws-cloudformation-database-cluster.git
git clone git@github.com:Senzing/aws-cloudformation-dev-rest.git
git clone git@github.com:Senzing/aws-cloudformation-ecs.git
git clone git@github.com:Senzing/aws-cloudformation-ecs-poc-simple.git
git clone git@github.com:Senzing/aws-cloudformation-ecs-senzing-stack-basic.git
git clone git@github.com:Senzing/aws-cloudformation-ecs-senzing-stack-choices.git
git clone git@github.com:Senzing/aws-lambda-cognito-authorizer.git
git clone git@github.com:Senzing/aws-lambda-self-signed-certificate.git
git clone git@github.com:Senzing/aws-marketplace-evaluation.git
git clone git@github.com:Senzing/azure-template-aks-poc-simple.git
git clone git@github.com:Senzing/certification.git
git clone git@github.com:Senzing/certified.git
git clone git@github.com:Senzing/charts.git
git clone git@github.com:Senzing/community-map.git
git clone git@github.com:Senzing/community-roadmap.git
git clone git@github.com:Senzing/compressedfile.git
git clone git@github.com:Senzing/configurator.git
git clone git@github.com:Senzing/connector-neo4j.git
git clone git@github.com:Senzing/data-encryption-aes256cbc-sample.git
git clone git@github.com:Senzing/data-mart-replicator.git
git clone git@github.com:Senzing/docker-adminer.git
git clone git@github.com:Senzing/docker-app-demo.git
git clone git@github.com:Senzing/docker-apt.git
git clone git@github.com:Senzing/docker-aptdownloader.git
git clone git@github.com:Senzing/docker-base-image-centos.git
git clone git@github.com:Senzing/docker-base-image-debian.git
git clone git@github.com:Senzing/docker-compose-air-gapper.git
git clone git@github.com:Senzing/docker-compose-aws-ecscli-demo.git
git clone git@github.com:Senzing/docker-compose-db2-cluster-demo.git
git clone git@github.com:Senzing/docker-compose-db2-demo.git
git clone git@github.com:Senzing/docker-compose-demo.git
git clone git@github.com:Senzing/docker-compose-mysql-demo.git
git clone git@github.com:Senzing/docker-compose-postgresql-demo.git
git clone git@github.com:Senzing/docker-compose-stream-loader-kafka-demo.git
git clone git@github.com:Senzing/docker-db2.git
git clone git@github.com:Senzing/docker-db2-driver-installer.git
git clone git@github.com:Senzing/docker-db2express-c.git
git clone git@github.com:Senzing/docker-g2command.git
git clone git@github.com:Senzing/docker-g2command-db2-cluster.git
git clone git@github.com:Senzing/docker-g2configtool.git
git clone git@github.com:Senzing/docker-g2loader.git
git clone git@github.com:Senzing/docker-g2loader-db2-cluster.git
git clone git@github.com:Senzing/docker-hello-world.git
git clone git@github.com:Senzing/docker-ibm-db2.git
git clone git@github.com:Senzing/docker-init-container.git
git clone git@github.com:Senzing/docker-installer.git
git clone git@github.com:Senzing/docker-jupyter.git
git clone git@github.com:Senzing/docker-mysql.git
git clone git@github.com:Senzing/docker-mysql-init.git
git clone git@github.com:Senzing/docker-opt-senzing.git
git clone git@github.com:Senzing/docker-poc-notebook.git
git clone git@github.com:Senzing/docker-python-3.6-base.git
git clone git@github.com:Senzing/docker-python-base-complete.git
git clone git@github.com:Senzing/docker-python-db2-base.git
git clone git@github.com:Senzing/docker-python-db2-cluster-base.git
git clone git@github.com:Senzing/docker-python-db2-cluster-demo.git
git clone git@github.com:Senzing/docker-python-demo.git
git clone git@github.com:Senzing/docker-python-mysql-base.git
git clone git@github.com:Senzing/docker-python-postgresql-base.git
git clone git@github.com:Senzing/docker-senzing-base.git
git clone git@github.com:Senzing/docker-senzing-console.git
git clone git@github.com:Senzing/docker-senzing-debug.git
git clone git@github.com:Senzing/docker-sshd.git
git clone git@github.com:Senzing/docker-terraform-aws.git
git clone git@github.com:Senzing/docker-test.git
git clone git@github.com:Senzing/docker-test-layers.git
git clone git@github.com:Senzing/docker-web-app-demo.git
git clone git@github.com:Senzing/docker-wrap-image-with-senzing-apt.git
git clone git@github.com:Senzing/docker-wrap-image-with-senzing-data.git
git clone git@github.com:Senzing/docker-xterm.git
git clone git@github.com:Senzing/docker-yum.git
git clone git@github.com:Senzing/docker-yumdownloader.git
git clone git@github.com:Senzing/dockerhub-util.git
git clone git@github.com:Senzing/dumpstack.git
git clone git@github.com:Senzing/elasticsearch.git
git clone git@github.com:Senzing/entity-search-web-app.git
git clone git@github.com:Senzing/entity-search-web-app-console.git
git clone git@github.com:Senzing/evaluate.git
git clone git@github.com:Senzing/g2-configuration-initializer.git
git clone git@github.com:Senzing/g2-python.git
git clone git@github.com:Senzing/g2-sdk-java.git
git clone git@github.com:Senzing/g2-sdk-python.git
git clone git@github.com:Senzing/g2anon.git
git clone git@github.com:Senzing/g2audit.git
git clone git@github.com:Senzing/g2command.git
git clone git@github.com:Senzing/g2config.git
git clone git@github.com:Senzing/g2configmgr.git
git clone git@github.com:Senzing/g2configtables.git
git clone git@github.com:Senzing/g2configtool.git
git clone git@github.com:Senzing/g2createinstance.git
git clone git@github.com:Senzing/g2createproject.git
git clone git@github.com:Senzing/g2database.git
git clone git@github.com:Senzing/g2diagnostic.git
git clone git@github.com:Senzing/g2engine.git
git clone git@github.com:Senzing/g2exception.git
git clone git@github.com:Senzing/g2explorer.git
git clone git@github.com:Senzing/g2export.git
git clone git@github.com:Senzing/g2hasher.git
git clone git@github.com:Senzing/g2health.git
git clone git@github.com:Senzing/g2iniparams.git
git clone git@github.com:Senzing/g2loader.git
git clone git@github.com:Senzing/g2module.git
git clone git@github.com:Senzing/g2paths.git
git clone git@github.com:Senzing/g2product.git
git clone git@github.com:Senzing/g2project.git
git clone git@github.com:Senzing/g2replicator.git
git clone git@github.com:Senzing/g2report.git
git clone git@github.com:Senzing/g2s3.git
git clone git@github.com:Senzing/g2search.git
git clone git@github.com:Senzing/g2service.git
git clone git@github.com:Senzing/g2setupconfig.git
git clone git@github.com:Senzing/g2snapshot.git
git clone git@github.com:Senzing/g2updateproject.git
git clone git@github.com:Senzing/g2vcompare.git
git clone git@github.com:Senzing/github-action-add-issue-to-project.git
git clone git@github.com:Senzing/github-action-identify-customer.git
git clone git@github.com:Senzing/github-util.git
git clone git@github.com:Senzing/governor-postgresql-transaction-id.git
git clone git@github.com:Senzing/hello-senzing-springboot-java.git
git clone git@github.com:Senzing/i2-senzing-connector.git
git clone git@github.com:Senzing/ibm-icp4d-guide.git
git clone git@github.com:Senzing/ibm-openshift-guide.git
git clone git@github.com:Senzing/images.git
git clone git@github.com:Senzing/java-g2loader.git
git clone git@github.com:Senzing/knowledge-base.git
git clone git@github.com:Senzing/kubernetes-demo.git
git clone git@github.com:Senzing/mapper-base.git
git clone git@github.com:Senzing/mapper-csv.git
git clone git@github.com:Senzing/mapper-dnb.git
git clone git@github.com:Senzing/mapper-dowjones.git
git clone git@github.com:Senzing/mapper-icij.git
git clone git@github.com:Senzing/mapper-leie.git
git clone git@github.com:Senzing/mapper-nomino.git
git clone git@github.com:Senzing/mapper-npi.git
git clone git@github.com:Senzing/mapper-ofac.git
git clone git@github.com:Senzing/mapper-openc.git
git clone git@github.com:Senzing/mapper-opensanctions.git
git clone git@github.com:Senzing/mapper-sayari.git
git clone git@github.com:Senzing/migrate.git
git clone git@github.com:Senzing/mock-data-generator.git
git clone git@github.com:Senzing/openshift-demo.git
git clone git@github.com:Senzing/packer-ansible.git
git clone git@github.com:Senzing/packer-senzing-demo-ubuntu-18.04.git
git clone git@github.com:Senzing/postgresql-client.git
git clone git@github.com:Senzing/postgresql-performance.git
git clone git@github.com:Senzing/rabbitmq-performance.git
git clone git@github.com:Senzing/rancher-demo.git
git clone git@github.com:Senzing/ready-for-senzing.git
git clone git@github.com:Senzing/redoer.git
git clone git@github.com:Senzing/resolver.git
git clone git@github.com:Senzing/rest-api-client-java.git
git clone git@github.com:Senzing/rest-api-client-ng.git
git clone git@github.com:Senzing/risk-score-calculator.git
git clone git@github.com:Senzing/sdk-components-ng.git
git clone git@github.com:Senzing/sdk-graph-components.git
git clone git@github.com:Senzing/senzing-api-server.git
git clone git@github.com:Senzing/senzing-commons-java.git
git clone git@github.com:Senzing/senzing-data-encryption-specification.git
git clone git@github.com:Senzing/senzing-entity-specification.git
git clone git@github.com:Senzing/senzing-environment.git
git clone git@github.com:Senzing/senzing-listener.git
git clone git@github.com:Senzing/senzing-package.git
git clone git@github.com:Senzing/senzing-poc-server.git
git clone git@github.com:Senzing/senzing-rest-api-specification.git
git clone git@github.com:Senzing/senzing-sdk-api-specification.git
git clone git@github.com:Senzing/senzing-up.git
git clone git@github.com:Senzing/senzing.github.io.git
git clone git@github.com:Senzing/senzinggo.git
git clone git@github.com:Senzing/spike-docker-store-based-images.git
git clone git@github.com:Senzing/stream-configuration.git
git clone git@github.com:Senzing/stream-file-utility.git
git clone git@github.com:Senzing/stream-loader.git
git clone git@github.com:Senzing/stream-logger.git
git clone git@github.com:Senzing/stream-producer.git
git clone git@github.com:Senzing/subway-map.git
git clone git@github.com:Senzing/support.git
git clone git@github.com:Senzing/template-ansible-role.git
git clone git@github.com:Senzing/template-docker.git
git clone git@github.com:Senzing/template-python.git
git clone git@github.com:Senzing/template-repository.git
git clone git@github.com:Senzing/test-ground.git
git clone git@github.com:Senzing/truth-sets.git
git clone git@github.com:Senzing/video.git
git clone git@github.com:Senzing/webapp-drillthrough-demo.git
