#!/usr/bin/env bash

# Generated on 2021-03-24 by https://github.com/Senzing/dockerhub-util dockerhub-util.py version: 1.0.0 update: 2021-02-22

export SENZING_HELM_VERSION_SENZING_COLIFER_SQLITE_WEB=1.1.3
export SENZING_HELM_VERSION_SENZING_DB2_CLIENT=0.2.1
export SENZING_HELM_VERSION_SENZING_IBM_DB2_DRIVER_INSTALLER=1.1.3
export SENZING_HELM_VERSION_SENZING_KAFKA_TEST_CLIENT=1.0.1
export SENZING_HELM_VERSION_SENZING_MYSQL_TOOLS=1.0.0
export SENZING_HELM_VERSION_SENZING_MYSQL_CLIENT=1.0.1
export SENZING_HELM_VERSION_SENZING_PHPMYADMIN=2.0.6
export SENZING_HELM_VERSION_SENZING_PHPPGADMIN=2.0.0
export SENZING_HELM_VERSION_SENZING_POSTGRESQL_CLIENT=1.0.2
export SENZING_HELM_VERSION_SENZING_RESOLVER=1.3.0
export SENZING_HELM_VERSION_SENZING_API_SERVER=1.3.0
export SENZING_HELM_VERSION_SENZING_BASE=1.3.0
export SENZING_HELM_VERSION_SENZING_CONFIGURATOR=1.3.0
export SENZING_HELM_VERSION_SENZING_CONSOLE=1.2.0
export SENZING_HELM_VERSION_SENZING_DEBUG=1.2.1
export SENZING_HELM_VERSION_SENZING_ENTITY_SEARCH_WEB_APP=1.2.1
export SENZING_HELM_VERSION_SENZING_HELLO_WORLD=1.0.1
export SENZING_HELM_VERSION_SENZING_HELLO_WORLD_ON_HUB_DOCKER_COM=1.0.1
export SENZING_HELM_VERSION_SENZING_IBM_DB2=1.0.4
export SENZING_HELM_VERSION_SENZING_INIT_CONTAINER=1.3.0
export SENZING_HELM_VERSION_SENZING_MOCK_DATA_GENERATOR=1.0.3
export SENZING_HELM_VERSION_SENZING_PACKAGE=1.0.0
export SENZING_HELM_VERSION_SENZING_REDOER=1.3.0
export SENZING_HELM_VERSION_SENZING_STREAM_LOADER=1.3.0
export SENZING_HELM_VERSION_SENZING_STREAM_PRODUCER=1.1.0
export SENZING_HELM_VERSION_SENZING_YUM=1.2.0
