#!/usr/bin/env bash

# Generated on 2021-06-11 by https://github.com/Senzing/dockerhub-util dockerhub-util.py version: 1.0.1 update: 2021-06-11

export SENZING_DOCKER_IMAGE_VERSION_ADMINER=1.0.0
export SENZING_DOCKER_IMAGE_VERSION_APT=1.0.4
export SENZING_DOCKER_IMAGE_VERSION_APT_DOWNLOADER=1.1.3
export SENZING_DOCKER_IMAGE_VERSION_DB2_DRIVER_INSTALLER=1.0.2
export SENZING_DOCKER_IMAGE_VERSION_ENTITY_SEARCH_WEB_APP=2.2.3
export SENZING_DOCKER_IMAGE_VERSION_G2COMMAND=1.4.1
export SENZING_DOCKER_IMAGE_VERSION_G2CONFIGTOOL=1.4.2
export SENZING_DOCKER_IMAGE_VERSION_G2LOADER=1.4.1
export SENZING_DOCKER_IMAGE_VERSION_INIT_CONTAINER=1.6.9
export SENZING_DOCKER_IMAGE_VERSION_JUPYTER=1.3.0
export SENZING_DOCKER_IMAGE_VERSION_PHPPGADMIN=1.0.0
export SENZING_DOCKER_IMAGE_VERSION_PORTAINER=latest
export SENZING_DOCKER_IMAGE_VERSION_POSTGRES=11.6
export SENZING_DOCKER_IMAGE_VERSION_POSTGRESQL_CLIENT=1.0.0
export SENZING_DOCKER_IMAGE_VERSION_PYTHON_DEMO=1.4.1
export SENZING_DOCKER_IMAGE_VERSION_RABBITMQ=3.8.2
export SENZING_DOCKER_IMAGE_VERSION_REDOER=1.3.7
export SENZING_DOCKER_IMAGE_VERSION_RESOLVER=1.3.2
export SENZING_DOCKER_IMAGE_VERSION_SENZING_API_SERVER=2.6.1
export SENZING_DOCKER_IMAGE_VERSION_SENZING_BASE=1.5.5
export SENZING_DOCKER_IMAGE_VERSION_SENZING_CONSOLE=1.0.1
export SENZING_DOCKER_IMAGE_VERSION_SENZING_DEBUG=1.3.5
export SENZING_DOCKER_IMAGE_VERSION_SQLITE_WEB=latest
export SENZING_DOCKER_IMAGE_VERSION_SSHD=1.2.0
export SENZING_DOCKER_IMAGE_VERSION_STREAM_LOADER=1.7.6
export SENZING_DOCKER_IMAGE_VERSION_STREAM_LOGGER=1.1.2
export SENZING_DOCKER_IMAGE_VERSION_STREAM_PRODUCER=1.4.0
export SENZING_DOCKER_IMAGE_VERSION_SWAGGERAPI_SWAGGER_UI=v3.50.0
export SENZING_DOCKER_IMAGE_VERSION_WEB_APP_DEMO=2.1.1
export SENZING_DOCKER_IMAGE_VERSION_XTERM=1.1.0
export SENZING_DOCKER_IMAGE_VERSION_YUM=1.1.4
export SENZING_DOCKER_IMAGE_VERSION_YUM_DOWNLOADER=1.2.0
