name: lint repo

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read
  pull-requests: read
  statuses: write

jobs:
  lint-code-base:
    uses: senzing-factory/build-resources/.github/workflows/linter.yaml@v2
